/* file: D:/AutoSar generated code/intvect_c0.c */
/* automatically generated by genRH850.exe, Version: 1.06 */
/* Configuration file: D:/PROJECT/VICP/OIL/OIL CFG/BASELINE_EXTEND_EVENT_NOOSTM.oil */
/* Generation time: Mon May 16 10:20:54 2016 */
/* Unlimited license CBD1500834 for Huizhou Desay SV Automotive, Product License, Instrument Panel */
/* Implementation: RH850_D1M */
/* Version of general code: 9.01.04 */

/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1	   Jan 02,2016    Initial version
*-----------------------------------------------------------------------
* 0.2	   Dec 20,2016   ShangQiuju Add config file according using hw.
*----------------------------------------------------------------------
* 0.3          Dec 21,2016    PEI Jingli    remove ds03h hw config,using test file instead of.
* ----------------------------------------------------------------------
* 0.4          Jan 05,2017    ZhangJie     Delete test code for NMI_TEST
* ----------------------------------------------------------------------
* 0.5          Jan 06,2017    ZhangJie     Repleace NMI exception handle function
* ----------------------------------------------------------------------
* 0.6          Feb 07,2017    ZhangJie     Change CAN ISR from channel 0 to 2.
*=====================================================================*/
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

#include "core_cfg.h"

#pragma asm

   .align 512
   .section ".osExceptionVectorTable_c0", "ax"

   .globl _osExceptionVectorTable_c0   /* start of the core exception vector table */
_osExceptionVectorTable_c0:

   .offset 0x0000
   .globl _RESET
   jr _RESET

   .offset 0x0010
   .globl _osCoreException_c0_0x0010
_osCoreException_c0_0x0010:
   jr _osUnhandledCoreException

   .offset 0x0020
   .globl _osCoreException_c0_0x0020
_osCoreException_c0_0x0020:
   jr _osUnhandledCoreException

   .offset 0x0030
   .globl _osCoreException_c0_0x0030
_osCoreException_c0_0x0030:
   jr _osUnhandledCoreException

   .offset 0x0040
   .globl _osCoreException_c0_0x0040
_osCoreException_c0_0x0040:
   jr _osTrapDispatcher_c0

   .offset 0x0050
   .globl _osCoreException_c0_0x0050
_osCoreException_c0_0x0050:
   jr _osUnhandledCoreException

   .offset 0x0060
   .globl _osCoreException_c0_0x0060
_osCoreException_c0_0x0060:
   jr _osUnhandledCoreException

   .offset 0x0070
   .globl _osCoreException_c0_0x0070
_osCoreException_c0_0x0070:
   jr _osUnhandledCoreException

   .offset 0x0080
   .globl _osCoreException_c0_0x0080
_osCoreException_c0_0x0080:
   jr _osUnhandledCoreException

   .offset 0x0090
   .globl _osCoreException_c0_0x0090
_osCoreException_c0_0x0090:
   jr _osUnhandledCoreException

   .offset 0x00a0
   .globl _osCoreException_c0_0x00a0
_osCoreException_c0_0x00a0:
   jr _osUnhandledCoreException

   .offset 0x00b0
   .globl _osCoreException_c0_0x00b0
_osCoreException_c0_0x00b0:
   jr _osUnhandledCoreException

   .offset 0x00c0
   .globl _osCoreException_c0_0x00c0
_osCoreException_c0_0x00c0:
   jr _osUnhandledCoreException

   .offset 0x00d0
   .globl _osCoreException_c0_0x00d0
_osCoreException_c0_0x00d0:
   jr _osUnhandledCoreException

   .offset 0x00e0
   .globl _osCoreException_c0_0x00e0
_osCoreException_c0_0x00e0:
   jr _FENMIHandler

   .offset 0x00f0
   .globl _osCoreException_c0_0x00f0
_osCoreException_c0_0x00f0:
   jr _osUnhandledCoreException

   .offset 0x0100
   .globl _osCoreException_c0_0x0100
_osCoreException_c0_0x0100:
   jr _osUnhandledDirectBranchException

   .offset 0x0110
   .globl _osCoreException_c0_0x0110
_osCoreException_c0_0x0110:
   jr _osUnhandledDirectBranchException

   .offset 0x0120
   .globl _osCoreException_c0_0x0120
_osCoreException_c0_0x0120:
   jr _osUnhandledDirectBranchException

   .offset 0x0130
   .globl _osCoreException_c0_0x0130
_osCoreException_c0_0x0130:
   jr _osUnhandledDirectBranchException

   .offset 0x0140
   .globl _osCoreException_c0_0x0140
_osCoreException_c0_0x0140:
   jr _osUnhandledDirectBranchException

   .offset 0x0150
   .globl _osCoreException_c0_0x0150
_osCoreException_c0_0x0150:
   jr _osUnhandledDirectBranchException

   .offset 0x0160
   .globl _osCoreException_c0_0x0160
_osCoreException_c0_0x0160:
   jr _osUnhandledDirectBranchException

   .offset 0x0170
   .globl _osCoreException_c0_0x0170
_osCoreException_c0_0x0170:
   jr _osUnhandledDirectBranchException		/*test WDT0 NMI INT*/
	//jr	_priority7_interrupt

   
   .offset 0x0180
   .globl _osCoreException_c0_0x0180
_osCoreException_c0_0x0180:
   jr _osUnhandledDirectBranchException

   .offset 0x0190
   .globl _osCoreException_c0_0x0190
_osCoreException_c0_0x0190:
   jr _osUnhandledDirectBranchException

   .offset 0x01a0
   .globl _osCoreException_c0_0x01a0
_osCoreException_c0_0x01a0:
   jr _osUnhandledDirectBranchException

   .offset 0x01b0
   .globl _osCoreException_c0_0x01b0
_osCoreException_c0_0x01b0:
   jr _osUnhandledDirectBranchException

   .offset 0x01c0
   .globl _osCoreException_c0_0x01c0
_osCoreException_c0_0x01c0:
   jr _osUnhandledDirectBranchException

   .offset 0x01d0
   .globl _osCoreException_c0_0x01d0
_osCoreException_c0_0x01d0:
   jr _osUnhandledDirectBranchException

   .offset 0x01e0
   .globl _osCoreException_c0_0x01e0
_osCoreException_c0_0x01e0:
   jr _osUnhandledDirectBranchException

   .offset 0x01f0
   .globl _osCoreException_c0_0x01f0
_osCoreException_c0_0x01f0:
   jr _osUnhandledDirectBranchException

   .globl _osExceptionVectorTableEnd_c0
_osExceptionVectorTableEnd_c0:   /* end of the core exception vector table */

#pragma endasm

#pragma asm

   .align 512
   .section ".osEIINTVectorTable_c0", "ax"

   .globl _osEIINTVectorTable_c0   /* start of the EIINT exception vector table */
_osEIINTVectorTable_c0:

   .word _osUnhandledEIINTException   	/* interrupt index = 0 */
   .word _osUnhandledEIINTException   	/* interrupt index = 1  Reserved*/
   .word _osUnhandledEIINTException   	/* interrupt index = 2  Reserved*/
   .word _osUnhandledEIINTException  	/* interrupt index = 3  Reserved*/
   .word _osUnhandledEIINTException   	/* interrupt index = 4  Reserved*/
   .word _osUnhandledEIINTException   	/* interrupt index = 5  Reserved*/
   .word _osUnhandledEIINTException   	/* interrupt index = 6  Reserved*/
   .word _osUnhandledEIINTException  	/* interrupt index = 7  Reserved*/
   .word _osUnhandledEIINTException   	/* interrupt index = 8 */
   .word _ISR_TAUD0I2_CAT2 			  	/* interrupt index = 9 */
   .word _osUnhandledEIINTException		/* interrupt index = 10 */
   .word _ISR_TAUD0I6_CAT2 			  	/* interrupt index = 11 */
   .word _osUnhandledEIINTException		/* interrupt index = 12 */
   .word _osUnhandledEIINTException		/* interrupt index = 13 */
   .word _osUnhandledEIINTException		/* interrupt index = 14 */
   .word _osUnhandledEIINTException		/* interrupt index = 15 */
   .word _osUnhandledEIINTException		/* interrupt index = 16 */
   .word _osUnhandledEIINTException		/* interrupt index = 17 */
   .word _ISR_ADCA0_INTSG1_CAT2      	/* interrupt index F1K = 18 */
   .word _osUnhandledEIINTException		/* interrupt index = 19 */
   .word _osUnhandledEIINTException		/* interrupt index = 20 */
   .word _osUnhandledEIINTException		/* interrupt index = 21 */
   .word _ISR_CANGERR_CAT2   			/* interrupt index F1K = 22 */
   .word _ISR_CANGRECC_CAT2 			/* interrupt index  F1K = 23 */
   .word _ISR_CAN0ERR_CAT2//_osUnhandledEIINTException		/* interrupt index = 24 */
   .word _osUnhandledEIINTException		/* interrupt index = 25 */
   .word _ISR_CAN0TRX_CAT2//_osUnhandledEIINTException		/* interrupt index = 26 */
   .word _osUnhandledEIINTException		/* interrupt index = 27 */
   .word _osUnhandledEIINTException		/* interrupt index = 28 */
   .word _ISR_CSIH0IC_CAT2				/* interrupt index  F1K = 29 */
   .word _ISR_CSIH0IR_CAT2              /* interrupt index  F1K = 30 */
   .word _ISR_CSIH0IRE_CAT2             /* interrupt index  F1K = 31 */
   .word _osUnhandledEIINTException		/* interrupt index = 32 */
   .word _osUnhandledEIINTException		/* interrupt index = 33 */
   .word _ISR_UART0_Tx_CAT2             /* interrupt index  F1K = 34 */
   .word _ISR_UART0_Rx_CAT2             /* interrupt index  F1K = 35 */
   .word _ISR_UART0_Error_CAT2          /* interrupt index  F1K = 36 */
   .word _osUnhandledEIINTException 	/* interrupt index  F1K = 37 */
   .word _osUnhandledEIINTException		/* interrupt index = 38 */
   .word _osUnhandledEIINTException		/* interrupt index = 39 */
   .word _ISR_WDTA0_CAT2                /* interrupt index = 40 */
   .word _osUnhandledEIINTException		/* interrupt index = 41 */
   .word _osUnhandledEIINTException		/* interrupt index = 42 */
   .word _ISR_INTP3_CAT2				/* interrupt index = 43 */
   .word _osUnhandledEIINTException		/* interrupt index = 44 */
   .word _ISR_INTP5_CAT2//_osUnhandledEIINTException		/* interrupt index = 45 */
   .word _ISR_INTP10_CAT2 				/* interrupt index = 46 */
   .word _osUnhandledEIINTException		/* interrupt index = 47 */
   .word _ISR_TAUD0I1_CAT2		/* interrupt index = 48 */
   .word _osUnhandledEIINTException		/* interrupt index = 49 */
   .word _osUnhandledEIINTException    	/* interrupt index = 50 */
   .word _osUnhandledEIINTException		/* interrupt index = 51 */
   .word _osUnhandledEIINTException		/* interrupt index = 52 */
   .word _osUnhandledEIINTException		/* interrupt index = 53 */
   .word _osUnhandledEIINTException    			/* interrupt index = 54  */
   .word _ISR_TAUD0I15_CAT2             /* interrupt index = 55  */
   .word _osUnhandledEIINTException		/* interrupt index = 56 */
   .word _osUnhandledEIINTException		/* interrupt index = 57 */
   .word _osUnhandledEIINTException		/* interrupt index = 58 */
   .word _osUnhandledEIINTException		/* interrupt index = 59 */
   .word _ISR_INTDMA0_CAT2		/* interrupt index = 60 -INTDMA0*/
   .word _ISR_INTDMA1_CAT2		/* interrupt index = 61 */
   .word _ISR_INTDMA2_CAT2		/* interrupt index = 62 */
   .word _ISR_INTDMA3_CAT2		/* interrupt index = 63 */
   .word _ISR_INTDMA4_CAT2		/* interrupt index = 64 */
   .word _ISR_INTDMA5_CAT2     /* interrupt index = 65  */
   .word _ISR_INTDMA6_CAT2		/* interrupt index = 66 */
   .word _ISR_INTDMA7_CAT2		/* interrupt index = 67*/
   .word _ISR_INTDMA8_CAT2		/* interrupt index = 68 */
   .word _ISR_INTDMA9_CAT2		/* interrupt index = 69 */
   .word _ISR_INTDMA10_CAT2		/* interrupt index = 70 */
   .word _ISR_INTDMA11_CAT2		/* interrupt index = 71 */
   .word _ISR_INTDMA12_CAT2		/* interrupt index = 72 */
   .word _ISR_INTDMA13_CAT2		/* interrupt index = 73 */
   .word _ISR_INTDMA14_CAT2		/* interrupt index = 74*/
   .word _ISR_INTDMA15_CAT2     /* interrupt index = 75  */
   .word _ISR_IIC0TI_CAT2               /* interrupt index = 76  */
   .word _ISR_IIC0EE_CAT2  				/* interrupt index = 77  */
   .word _ISR_IIC0RI_CAT2               /* interrupt index = 78  */
   .word _ISR_IIC0TEI_CAT2              /* interrupt index = 79  */
   .word _osUnhandledEIINTException     /* interrupt index = 80  */
   .word _ISR_TAUJ0I1_CAT2              /* interrupt index = 81  */
   .word _osUnhandledEIINTException              /* interrupt index = 82  */
   .word _osUnhandledEIINTException			 	/* interrupt index = 83  */
   .word _ISR_OSTM0_CAT2                /* interrupt index = 84 */
   .word _osUnhandledEIINTException		/* interrupt index = 85 */
   .word _osUnhandledEIINTException		/* interrupt index = 86 */
   .word _osUnhandledEIINTException		/* interrupt index = 87 */
   .word _osUnhandledEIINTException		/* interrupt index = 88 */
   .word _osUnhandledEIINTException		/* interrupt index = 89 */
   .word _osUnhandledEIINTException		/* interrupt index = 90 */
   .word _osUnhandledEIINTException		/* interrupt index = 91 */
   .word _osUnhandledEIINTException		/* interrupt index = 92 */
   .word _osUnhandledEIINTException		/* interrupt index = 93 */
   .word _osUnhandledEIINTException		/* interrupt index = 94 */
   .word _osUnhandledEIINTException		/* interrupt index = 95 */
   .word _osUnhandledEIINTException		/* interrupt index = 96 */
   .word _osUnhandledEIINTException		/* interrupt index = 97 */
   .word _osUnhandledEIINTException		/* interrupt index = 98 */
   .word _osUnhandledEIINTException		/* interrupt index = 99 */
   .word _osUnhandledEIINTException		/* interrupt index = 100 */
   .word _osUnhandledEIINTException		/* interrupt index = 101 */
   .word _osUnhandledEIINTException		/* interrupt index = 102 */
   .word _osUnhandledEIINTException		/* interrupt index = 103 */
   .word _osUnhandledEIINTException		/* interrupt index = 104 */
   .word _osUnhandledEIINTException		/* interrupt index = 105 */
   .word _osUnhandledEIINTException		/* interrupt index = 106 */
   .word _osUnhandledEIINTException		/* interrupt index = 107 */
   .word _osUnhandledEIINTException		/* interrupt index = 108 */
   .word _osUnhandledEIINTException		/* interrupt index = 109 */
   .word _osUnhandledEIINTException		/* interrupt index = 110 */
   .word _osUnhandledEIINTException		/* interrupt index = 111 */
   .word _osUnhandledEIINTException		/* interrupt index = 112 */
   .word _ISR_CAN1ERR_CAT2				/* interrupt index = 113 */
   .word _osUnhandledEIINTException		/* interrupt index = 114 */
   .word _ISR_CAN1TRX_CAT2				/* interrupt index = 115 */
   .word _ISR_CSIH1IC_CAT2				/* interrupt index = 116  */
   .word _ISR_CSIH1IR_CAT2				/* interrupt index = 117  */
   .word _ISR_CSIH1IRE_CAT2				/* interrupt index = 118 */
   .word _osUnhandledEIINTException		/* interrupt index = 119 */
   .word _osUnhandledEIINTException		/* interrupt index = 120 */
   .word _ISR_UART1_Tx_CAT2             /* interrupt index = 121  */
   .word _ISR_UART1_Rx_CAT2				/* interrupt index = 122 */
   .word _ISR_UART1_Error_CAT2			/* interrupt index = 123 */
   .word _osUnhandledEIINTException		/* interrupt index = 124*/
   .word _osUnhandledEIINTException		/* interrupt index = 125 */
   .word _osUnhandledEIINTException		/* interrupt index = 126 */
   .word _osUnhandledEIINTException		/* interrupt index = 127 */
   .word _ISR_INTP6_CAT2                /* interrupt index = 128 */
   .word _osUnhandledEIINTException		/* interrupt index = 129 */
   .word _osUnhandledEIINTException		/* interrupt index = 130 */
   .word _osUnhandledEIINTException		/* interrupt index = 131 */
   .word _osUnhandledEIINTException		/* interrupt index = 132 */
   .word _osUnhandledEIINTException		/* interrupt index = 133 */
   .word _osUnhandledEIINTException		/* interrupt index = 134 */
   .word _osUnhandledEIINTException		/* interrupt index = 135 */
   .word _osUnhandledEIINTException		/* interrupt index = 136 */
   .word _osUnhandledEIINTException		/* interrupt index = 137 */
   .word _osUnhandledEIINTException		/* interrupt index = 138 */
   .word _osUnhandledEIINTException		/* interrupt index = 139 */
   .word _osUnhandledEIINTException		/* interrupt index = 140 */
   .word _osUnhandledEIINTException		/* interrupt index = 141 */
   .word _ISR_TAUB0I0_CAT2              /* interrupt index = 142 */
   .word _osUnhandledEIINTException		/* interrupt index = 143 */
   .word _ISR_TAUB0I2_CAT2  			/* interrupt index = 144 */
   .word _osUnhandledEIINTException		/* interrupt index = 145 */
   .word _ISR_TAUB0I4_CAT2				/* interrupt index = 146 */
   .word _ISR_TAUB0I5_CAT2  	 		/* interrupt index = 147 */
   .word _ISR_TAUB0I6_CAT2				/* interrupt index = 148 */
   .word _ISR_TAUB0I7_CAT2              /* interrupt index = 149  */
   .word _ISR_TAUB0I8_CAT2              /* interrupt index = 150  */
   .word _osUnhandledEIINTException		/* interrupt index = 151  */
   .word _ISR_TAUB0I10_CAT2             /* interrupt index = 152  */
   .word _ISR_TAUB0I11_CAT2				/* interrupt index = 153  */
   .word _ISR_TAUB0I12_CAT2              /* interrupt index  F1K = 154  */
   .word _ISR_TAUB0I13_CAT2              /* interrupt index  F1K = 155  */
   .word _ISR_TAUB0I14_CAT2              /* interrupt index  F1K = 156  */
   .word _ISR_TAUB0I15_CAT2              /* interrupt index  F1K = 157  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 158  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 159  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 160  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 161  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 162  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 163  */
   .word _osUnhandledEIINTException		 /* interrupt index  F1K = 164  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 165  */    
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 166  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 167  */
   .word _ISR_TAUJ1I0_CAT2				/* interrupt index  F1K = 168  */
   .word _ISR_TAUJ1I1_CAT2		/* interrupt index  F1K = 169  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 170  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 171  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 172  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 173  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 174  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 175  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 176  */ 
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 177  */
   .word _ISR_TAUJ1I2_CAT2   			/* interrupt index  F1K = 178  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 179  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 180  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 181  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 182  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 183  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 184  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 185  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 186  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 187  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 188  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 189  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 190  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 191  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 192  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 193  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 194  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 195  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 196  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 197  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 198  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 199  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 200  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 201  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 202  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 203  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 204  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 205  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 206  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 207  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 208  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 209  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 210  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 211  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 212  */
   .word _ISR_ADCA1_INTSG1_CAT2			/* interrupt index  F1K = 213  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 214  */
   .word _osUnhandledEIINTException 	/* interrupt index  F1K = 215  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 216  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 217  */			
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 218  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 219  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 220  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 221  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 222  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 223  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 224  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 225  */
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 226  */         
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 227  */         
   .word _osUnhandledEIINTException		/* interrupt index  F1K = 228  */                    
   .word _ISR_UART3_Tx_CAT2				/* interrupt index uart for eol F1K = 229  */
   .word _ISR_UART3_Rx_CAT2				/* interrupt index uart for eol F1K = 230  */
   .word _ISR_UART3_Error_CAT2			/* interrupt index uart for eol F1K = 231  */
   .word _osUnhandledEIINTException		/* interrupt index = 232  */
   .word _ISR_UART4_Tx_CAT2				/* interrupt index uart for M4UART F1K = 233  */
   .word _ISR_UART4_Rx_CAT2				/* interrupt index uart for M4UART F1K = 234  */
   .word _ISR_UART4_Error_CAT2			/* interrupt index uart for M4UART F1K = 235  */
   .word _osUnhandledEIINTException		/* interrupt index = 236  */
   .word _osUnhandledEIINTException		/* interrupt index = 237  */
   .word _osUnhandledEIINTException		/* interrupt index = 238  */
   .word _osUnhandledEIINTException		/* interrupt index = 239  */ 
   .word _osUnhandledEIINTException		/* interrupt index = 240  */ 
   .word _osUnhandledEIINTException		/* interrupt index = 241  */
   .word _osUnhandledEIINTException		/* interrupt index = 242  */
   .word _osUnhandledEIINTException		/* interrupt index = 243  */
   .word _osUnhandledEIINTException		/* interrupt index = 244  */
   .word _osUnhandledEIINTException		/* interrupt index = 245  */
   .word _osUnhandledEIINTException		/* interrupt index = 246  */
   .word _osUnhandledEIINTException		/* interrupt index = 247  */
   .word _osUnhandledEIINTException		/* interrupt index = 248  */
   .word _osUnhandledEIINTException		/* interrupt index = 249  */			
   .word _osUnhandledEIINTException		/* interrupt index = 250  */
   .word _osUnhandledEIINTException		/* interrupt index = 251  */
   .word _osUnhandledEIINTException		/* interrupt index = 252  */
   .word _osUnhandledEIINTException		/* interrupt index = 253  */
   .word _osUnhandledEIINTException		/* interrupt index = 254  */
   .word _osUnhandledEIINTException		/* interrupt index = 255  */
   .word _osUnhandledEIINTException		/* interrupt index = 256  */
   .word _osUnhandledEIINTException		/* interrupt index = 257  */
   .word _osUnhandledEIINTException		/* interrupt index = 258  */
   .word _osUnhandledEIINTException		/* interrupt index = 259  */			
   .word _osUnhandledEIINTException		/* interrupt index = 260  */
   .word _osUnhandledEIINTException		/* interrupt index = 261  */
   .word _osUnhandledEIINTException		/* interrupt index = 262  */
   .word _osUnhandledEIINTException		/* interrupt index = 263  */
   .word _osUnhandledEIINTException		/* interrupt index = 264  */  
   .word _osUnhandledEIINTException		/* interrupt index = 265  */
   .word _osUnhandledEIINTException		/* interrupt index = 266  */
   .word _osUnhandledEIINTException		/* interrupt index = 267  */
   .word _osUnhandledEIINTException		/* interrupt index = 268  */
   .word _osUnhandledEIINTException		/* interrupt index = 269  */			
   .word _osUnhandledEIINTException		/* interrupt index = 270  */
   .word _osUnhandledEIINTException		/* interrupt index = 271  */
   .word _osUnhandledEIINTException		/* interrupt index = 273  */
   .word _osUnhandledEIINTException		/* interrupt index = 274  */
   .word _osUnhandledEIINTException		/* interrupt index = 275  */
   .word _osUnhandledEIINTException		/* interrupt index = 276  */
   .word _osUnhandledEIINTException		/* interrupt index = 277  */
   .word _osUnhandledEIINTException		/* interrupt index = 278  */
   .word _osUnhandledEIINTException		/* interrupt index = 279  */
   .word _osUnhandledEIINTException		/* interrupt index = 280  */			
   .word _osUnhandledEIINTException		/* interrupt index = 281  */
   .word _osUnhandledEIINTException		/* interrupt index = 282  */
   .word _osUnhandledEIINTException		/* interrupt index = 283  */
   .word _osUnhandledEIINTException		/* interrupt index = 284  */
   .word _osUnhandledEIINTException		/* interrupt index = 285  */
   .word _osUnhandledEIINTException		/* interrupt index = 286  */
   .word _osUnhandledEIINTException		/* interrupt index = 287  */
   .word _osUnhandledEIINTException		/* interrupt index = 288  */
   .word _osUnhandledEIINTException		/* interrupt index = 289  */ 
   
   .globl _osEIINTVectorTableEnd_c0
_osEIINTVectorTableEnd_c0:   /* end of the EIINT exception vector table */

#pragma endasm

#pragma asm

   	.section ".os_text", "ax"

   	/* MISRA RULE 14.1 not violated: ISR_TAUD0I0 is branched via EIINT vector table. */
    osCAT2ISRC0(ISR_TAUD0I15, 0) /* PRQA S 1503 */
	osCAT2ISRC0(ISR_IIC0RI,3)
	osCAT2ISRC0(ISR_IIC0TI,3)
	osCAT2ISRC0(ISR_IIC0TEI,3)
	osCAT2ISRC0(ISR_IIC0EE,3)
	osCAT2ISRC0(ISR_ADCA0_INTSG1,3)
	osCAT2ISRC0(ISR_ADCA1_INTSG1,3)
	osCAT2ISRC0(ISR_CSIH1IC,3)	
	osCAT2ISRC0(ISR_CSIH1IR,3)
	osCAT2ISRC0(ISR_CSIH1IRE,3)
	
	osCAT2ISRC0(ISR_CSIH0IC,3)	
	osCAT2ISRC0(ISR_CSIH0IR,3)
	osCAT2ISRC0(ISR_CSIH0IRE,3)
	osCAT2ISRC0(ISR_UART0_Tx,3)
	osCAT2ISRC0(ISR_UART0_Rx,3)
	osCAT2ISRC0(ISR_UART0_Error,3)
	osCAT2ISRC0(ISR_OSTM0,3)

    osCAT2ISRC0(ISR_INTP5, 3) //uidq1158
    osCAT2ISRC0(ISR_INTP10, 3) //uidq1158
	osCAT2ISRC0(ISR_INTP6, 3)
   osCAT2ISRC0(ISR_INTP3, 3)//uidq1158

	osCAT2ISRC0(ISR_UART1_Tx,3)//uidq1158
	osCAT2ISRC0(ISR_UART1_Rx,3)
	osCAT2ISRC0(ISR_UART1_Error,3)//uidq1158
	//remove by uidq1158
/*
	osCAT2ISRC0(ISR_UART2_Tx,1)
	osCAT2ISRC0(ISR_UART2_Rx,1)
	osCAT2ISRC0(ISR_UART2_Error,1)
	osCAT2ISRC0(ISR_UART3_Tx,1)
	osCAT2ISRC0(ISR_UART3_Rx,1)
	osCAT2ISRC0(ISR_UART3_Error,1)
*/
   /* MISRA RULE 14.1 not violated: ISR_CANGERR is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CANGERR, 3) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_CANGRECC is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CANGRECC, 3) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_CAN0ERR is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CAN0ERR, 3) /* PRQA S 1503 *///1158

   /* MISRA RULE 14.1 not violated: ISR_CAN0TRX is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CAN0TRX, 3) /* PRQA S 1503 *///1158


	  /* MISRA RULE 14.1 not violated: ISR_CAN0ERR is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CAN1ERR, 3) /* PRQA S 1503 *///1158

   /* MISRA RULE 14.1 not violated: ISR_CAN0TRX is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_CAN1TRX, 3) /* PRQA S 1503 *///1158
   /* MISRA RULE 14.1 not violated: ISR_WDTA0 is branched via EIINT vector table. */


   osCAT2ISRC0(ISR_WDTA0, 3) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_TAUJ0I0 is branched via EIINT vector table. */
 //  osCAT2ISRC0(ISR_TAUJ0I0, 2) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_TAUB0I0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_TAUB0I0, 1) /* PRQA S 1503 */

   /* MISRA RULE 14.1 not violated: ISR_TAUJ1I0 is branched via EIINT vector table. */
   osCAT2ISRC0(ISR_TAUJ1I0, 3) /* PRQA S 1503 */

    osCAT2ISRC0(ISR_TAUD0I6, 3) /*26  TAUD0I1 */
    osCAT2ISRC0(ISR_TAUJ1I2, 3) /*27 TAUD0I2 */
    osCAT2ISRC0(ISR_TAUD0I2, 3) /* TAUD0I2 */
    osCAT2ISRC0(ISR_TAUB0I11, 3) /*TAUB0I11*/

    osCAT2ISRC0(ISR_TAUB0I2,1)
    osCAT2ISRC0(ISR_TAUB0I4,1)
	osCAT2ISRC0(ISR_TAUB0I5,1)
	osCAT2ISRC0(ISR_TAUB0I6,1)
	osCAT2ISRC0(ISR_TAUB0I7,1)
	osCAT2ISRC0(ISR_TAUB0I8,1)
	osCAT2ISRC0(ISR_TAUB0I10,1)
	osCAT2ISRC0(ISR_TAUB0I12,1)
	osCAT2ISRC0(ISR_TAUB0I13,1)
	osCAT2ISRC0(ISR_TAUB0I14,1)
	osCAT2ISRC0(ISR_TAUB0I15,1)
	

//UART for eol
	osCAT2ISRC0(ISR_UART3_Tx,3)
	osCAT2ISRC0(ISR_UART3_Rx,3)
	osCAT2ISRC0(ISR_UART3_Error,3)

//UART for m4
	osCAT2ISRC0(ISR_UART4_Tx,3)
	osCAT2ISRC0(ISR_UART4_Rx,3)
	osCAT2ISRC0(ISR_UART4_Error,3)

	osCAT2ISRC0(ISR_TAUD0I1,4)
	osCAT2ISRC0(ISR_TAUJ0I1,2)

	osCAT2ISRC0(ISR_TAUJ1I1,2)
	
    osCAT2ISRC0(ISR_INTDMA0,3)
    osCAT2ISRC0(ISR_INTDMA1,3)
    osCAT2ISRC0(ISR_INTDMA2,3)
    osCAT2ISRC0(ISR_INTDMA3,3)
    osCAT2ISRC0(ISR_INTDMA4,3)
    osCAT2ISRC0(ISR_INTDMA5,3)
    osCAT2ISRC0(ISR_INTDMA6,3)
    osCAT2ISRC0(ISR_INTDMA7,3)
    osCAT2ISRC0(ISR_INTDMA8,3)
    osCAT2ISRC0(ISR_INTDMA9,3)
    osCAT2ISRC0(ISR_INTDMA10,3)
    osCAT2ISRC0(ISR_INTDMA11,3)
    osCAT2ISRC0(ISR_INTDMA12,3)
    osCAT2ISRC0(ISR_INTDMA13,3)
    osCAT2ISRC0(ISR_INTDMA14,3)
    osCAT2ISRC0(ISR_INTDMA15,3)




#pragma endasm

