/***********************************************************************
*   Copyright (C) Huizhou Desay SV Automotive Co., Ltd.				   *
*				  All Rights Reserved.          					   *
*   Department : RN R&D SW1      									   *
*   AUTHOR	   : Shao Guangxian										   *
************************************************************************
* Object        :
* Module        :
* Instance      :
* Description   :
* file: D:/AutoSar generated code/osConfigBlock.c 
* automatically generated by genRH850.exe, Version: 1.06 
* Configuration file: D:/PROJECT/VICP/OIL/OIL CFG/BASELINE_EXTEND_EVENT_NOOSTM.oil 
* Generation time: Mon May 16 15:29:05 2016 
* Unlimited license CBD1500834 for Huizhou Desay SV Automotive, Product License, Instrument Panel 
* Implementation: RH850_D1M 
* Version of general code: 9.01.04 
*-----------------------------------------------------------------------
* Version:
* Date:
* Author:
***********************************************************************/
/*-History--------------------------------------------------------------
* Version       Date    Name    Changes and comments
*-----------------------------------------------------------------------
* 0.1	   Jan 02,2016    Initial version
*-----------------------------------------------------------------------
* 0.2	   Dec 20,2016   ShangQiuju Add config file according using hw.
 ----------------------------------------------------------------------
* 0.3          Dec 21,2016    PEI Jingli    remove ds03h hw config,using test file instead of.
* ----------------------------------------------------------------------
* 0.4          Feb 07,2017    ZhangJie     Change CAN ISR from channel 0 to 2.
* ----------------------------------------------------------------------
* 0.5          Apr 13,2017    ZhangJie     Fix intp-isr.
*=====================================================================*/

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#define osdVrmGenMajRelNum 1
#define osdVrmGenMinRelNum 6
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osStacks.h"
#else
 #include <osStacks.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif

#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

#pragma ghs section rodata=".os_rodata"
#pragma ghs section rosdata=".os_rosdata"

/* MISRA RULE 8.10 VIOLATION: osConfigBlock is accessed by several modules in many configurations.
*  Declaring this variable static in the other cases would increase code complexity too much.
*/
osqROM0 osqROM1 const osqROM2 tsConfigBlock osqROM3 osConfigBlock = /* PRQA S 1504 */ 
{
   /* Frame */
   {0x82, 0x2A, 0x0C, 0xC4}, /* aucMagicNumber */
   (osuint16)((((sizeof(osConfigBlock)) & 0xFF) << 8)|
              (( sizeof(osConfigBlock))         >> 8)), /* Length (little endian) */
   9,
   osdVrmMajRelNumRef,    /* MajorVersion */
   osdVrmMinRelNumRef,    /* MinorVersion */
   (osuint16)3,           /* ConfigBlockVersion */
   (osuint16)1, /* UserConfigVersion */
   /* cargo --------------------------------------------------------------- */
   &osConfigBlock,
   /* start addresses of sub-containers (fixed number) */
   &(osConfigBlock.uiNumberOfTasks),        /* Sub-Container 0 */
   (osConfigBlock.aulTaskStartAddress),     /* Sub-Container 1 */
   (osConfigBlock.aucTaskPreemptive),       /* Sub-Container 2 */
   (osConfigBlock.aucTaskTrusted),          /* Sub-Container 3 */
   (osConfigBlock.aulTaskStackStartAddress),/* Sub-Container 4 */
   (osConfigBlock.aulTaskStackEndAddress),  /* Sub-Container 5 */
   (osConfigBlock.acTaskToAppl),            /* Sub-Container 6 */
   (osConfigBlock.aucIsrTrusted),           /* Sub-Container 7 */
   (osConfigBlock.acIsrToAppl),             /* Sub-Container 8 */
   (osConfigBlock.applTrusted),             /* Sub-Container 9 */
   (osConfigBlock.trustedFunctions),        /* Sub-Container 10 */
   (osConfigBlock.nonTrustedFunctions),     /* Sub-Container 11 */
   (osConfigBlock.cat2IsrStartAddress),     /* Sub-Container 12 */
   (osConfigBlock.IsrNestable),             /* Sub-Container 13 */
   (osConfigBlock.ProcessToCore),           /* Sub-Container 14 */
   (osConfigBlock.AlarmToCore),             /* Sub-Container 15 */
   (osConfigBlock.ResourceToCore),          /* Sub-Container 16 */
   (osConfigBlock.CounterToCore),           /* Sub-Container 17 */
   (osConfigBlock.ScheduleTableToCore),     /* Sub-Container 18 */
   (osConfigBlock.ApplicationToCore),       /* Sub-Container 19 */
   (osConfigBlock.TrustedFunctionToCore),   /* Sub-Container 20 */
   (osConfigBlock.NonTrustedFunctionToCore),/* Sub-Container 21 */
   (osConfigBlock.CcbAddress),              /* Sub-Container 22 */
   (osConfigBlock.peripheralRegions),       /* Sub-Container 23 */
   (osConfigBlock.SpinlockLockMethods),     /* Sub-Container 24 */
   (osConfigBlock.SpinlockLockTypes),       /* Sub-Container 25 */
   (osConfigBlock.OptimizedSpinlockVars),   /* Sub-Container 26 */
   (osConfigBlock.osCat2IsrStacks),         /* Sub-Container 27 */
   (osConfigBlock.osIsrChannel),            /* Sub-Container 28 */
   (osConfigBlock.osIsrPrioLevel),          /* Sub-Container 29 */
   (osConfigBlock.osIsrToCore),             /* Sub-Container 30 */
   /* Sub-Container 0 */
   osdNumberOfAllTasks,
   osdNumberOfCat2ISRs,
   osdNumberOfTrustedFunctions,
   0,
   osdNumberOfApplications,
   0,
   osdStackUsageMeasurement,
   osdNumberOfAlarms,
   osdNumberOfAllResources,
   osdNumberOfAvailableCores,
   osdNumberOfCounters,
   osdNumberOfProcesses,
   osdNumberOfScheduleTables,
   0,

   {
      {(osStackPtrType)osdSystemStack_c0_BOT, (osStackPtrType)osdSystemStack_c0_TOP},
   },

   /* Sub-Container 1, task start addresses */
   {       
      &BasicTaskEntry,		
      &BasicTaskEntry,
      /*&BasicTaskEntry,*/
      &ExtendTaskEntry,
      &BasicTaskEntry,
      /*&BasicTaskEntry,*/
      &ExtendTaskEntry,
      &BasicTaskEntry,
      &BasicTaskEntry,
      &BasicTaskEntry,
      &InitTaskEntry,
       /*
      &SystemSwitchHighfunc,
      &FastCyclicfunc,
      &EventTaskfunc,
      &SlowCyclicfunc,
      &SlowJobfunc,
      &SystemSwitchLowfunc,
      &ResetTaskfunc,
      */
      (osTaskFctType)0
   },
   /* Sub-Container 2, task preemptiveness */
   {
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      0
   },
   /* Sub-Container 3, task trusted */
   {
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
   },
   /* Sub-Container 4, stack start address */
   {
      (osStackPtrType)osdSystemSwitchHigh_BOT,
      (osStackPtrType)osdFastCyclic_BOT,
      (osStackPtrType)osdEventTask_BOT,
      (osStackPtrType)osdSlowCyclic_BOT,
      (osStackPtrType)osdSlowJob_BOT,
      (osStackPtrType)osdSystemSwitchLow_BOT,
      (osStackPtrType)osdUltraRadarFastTask_BOT,
      (osStackPtrType)osdUltraRadarSlowTask_BOT,
      (osStackPtrType)osdResetTask_BOT,
      (osStackPtrType)0
   },
   /* Sub-Container 5, stack end addresses */
   {
      (osStackPtrType)osdSystemSwitchHigh_TOP,
      (osStackPtrType)osdFastCyclic_TOP,
      (osStackPtrType)osdEventTask_TOP,
      (osStackPtrType)osdSlowCyclic_TOP,
      (osStackPtrType)osdSlowJob_TOP,
      (osStackPtrType)osdSystemSwitchLow_TOP,
      (osStackPtrType)osdUltraRadarFastTask_TOP,
      (osStackPtrType)osdUltraRadarSlowTask_TOP,
      (osStackPtrType)osdResetTask_TOP,
      (osStackPtrType)0
   },
   /* Sub-Container 6, translation table: task -> os-application */
   {
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 7, isr trusted */
   {
	  0,		 // CANGERR 		  1
	  0,		 // INTP10			  2
	  0,		 // CAN1TRX 		  3
	  0,		 // CAN1ERR 		  4
	  0,		 // CANGRECC		  5
	  0,		 // TAUB0I0 		  6
	  0,		 // TAUD0I15		  7
	// 0,		 // TAUJ0I0 		  8
	  0,		 // TAUJ1I0 		  9
	  0,		 // WDTA0			  10
	  0,		 // CSIH0IR 		  11
	  0,		 // IIC0TI			  12
	  0,		 // IIC0TEI 		  13
	  0,		 // IIC0EE			  14
	  0,		 // ADCA0_INTSG1	  15
	  0,		 // CSIH1IR 		  16
	  0,		 // CSIH1IC 		  17
	  0,		 // UART0_Tx_		  18
	  0,		 // UART0_Rx_		  19
	  0,		 // UART0_Error 	  20
	  0,		 // OSTM0			  21
	  0,		 // CSIH0IR 		  22
	  0,		 // CSIH0IC 		  23
	  0,		 // CSIH0IRE		  24
	  0,		 // CSIH1IRE		  25
	  0,		 // TAUD0I6 		  26
	  0,		 // TAUD0I2 		  27
	  0,		 // INTP6			  28
	  0,		 // TAUJ1I2 		  29
	  0,		 // UART1_Tx_		  30
	  0,		 // UART1_Rx_		  31
	  0,		 // UART1_Error 	  32
	  0,		 // INTP3			  33
	  0,		 // TAUB0I11		  34
	  0,		 // ADCA1_INTSG1	  35
	  0,		 // TAUB0I2 		  36
	  0,		 // TAUB0I4 		  37
	  0,		 // TAUB0I5 		  38
	  0,		 // TAUB0I6 		  39
	  0,		 // TAUB0I7 		  40
	  0,		 // TAUB0I8 		  41
	  0,		 // TAUB0I10		  42
	  0,		 // TAUB0I12		  43
	  0,		 // TAUB0I13		  44
	  0,		 // TAUB0I14		  45//
	  0,		 // TAUB0I15		  46//
	  0,		 // UART3_Tx_		  47
	  0,		 // UART3_Rx_		  48
	  0,		 // UART3_Error 	  49
	  0,		//TAUD0I1     1ms_USS_CT
	  0,		//TAUJ0I1     fixable_USS_CT
	  0,		// TAUJ1I1
      0,        //INTDMA0
      0,        //INTDMA1
      0,        //INTDMA2
      0,        //INTDMA3
      0,        //INTDMA4
      0,        //INTDMA5
      0,        //INTDMA6
      0,        //INTDMA7
      0,        //INTDMA8
      0,        //INTDMA9
      0,        //INTDMA10
      0,        //INTDMA11
      0,        //INTDMA12
      0,        //INTDMA13
      0,        //INTDMA14
      0,        //INTDMA15
      0
   },
   /* Sub-Container 8, translation table: isr -> os-application */
   {
      INVALID_OSAPPLICATION,		 // CANGERR 		  1
	  INVALID_OSAPPLICATION,		 // INTP10			  2
	  INVALID_OSAPPLICATION,		 // CAN1TRX 		  3
	  INVALID_OSAPPLICATION,		 // CAN1ERR 		  4
	  INVALID_OSAPPLICATION,		 // CANGRECC		  5
	  INVALID_OSAPPLICATION,		 // TAUB0I0 		  6
	  INVALID_OSAPPLICATION,		 // TAUD0I15		  7
	  //INVALID_OSAPPLICATION,		 // TAUJ0I0 		  8
	  INVALID_OSAPPLICATION,		 // TAUJ1I0 		  9
	  INVALID_OSAPPLICATION,		 // WDTA0			  10
	  INVALID_OSAPPLICATION,		 // CSIH0IR 		  11
	  INVALID_OSAPPLICATION,		 // IIC0TI			  12
	  INVALID_OSAPPLICATION,		 // IIC0TEI 		  13
	  INVALID_OSAPPLICATION,		 // IIC0EE			  14
	  INVALID_OSAPPLICATION,		 // ADCA0_INTSG1	  15
	  INVALID_OSAPPLICATION,		 // CSIH1IR 		  16
	  INVALID_OSAPPLICATION,		 // CSIH1IC 		  17
	  INVALID_OSAPPLICATION,		 // UART0_Tx_		  18
	  INVALID_OSAPPLICATION,		 // UART0_Rx_		  19
	  INVALID_OSAPPLICATION,		 // UART0_Error 	  20
	  INVALID_OSAPPLICATION,		 // OSTM0			  21
	  INVALID_OSAPPLICATION,		 // CSIH0IR 		  22
	  INVALID_OSAPPLICATION,		 // CSIH0IC 		  23
	  INVALID_OSAPPLICATION,		 // CSIH0IRE		  24
	  INVALID_OSAPPLICATION,		 // CSIH1IRE		  25
	  INVALID_OSAPPLICATION,		 // TAUD0I6 		  26
	  INVALID_OSAPPLICATION,		 // TAUD0I2 		  27
	  INVALID_OSAPPLICATION,		 // INTP6			  28
	  INVALID_OSAPPLICATION,		 // TAUJ1I2 		  29
	  INVALID_OSAPPLICATION,		 // UART1_Tx_		  30
	  INVALID_OSAPPLICATION,		 // UART1_Rx_		  31
	  INVALID_OSAPPLICATION,		 // UART1_Error 	  32
	  INVALID_OSAPPLICATION,		 // INTP3			  33
	  INVALID_OSAPPLICATION,		 // TAUB0I11		  34
	  INVALID_OSAPPLICATION,		 // ADCA1_INTSG1	  35
	  INVALID_OSAPPLICATION,		 // TAUB0I2 		  36
	  INVALID_OSAPPLICATION,		 // TAUB0I4 		  37
	  INVALID_OSAPPLICATION,		 // TAUB0I5 		  38
	  INVALID_OSAPPLICATION,		 // TAUB0I6 		  39
	  INVALID_OSAPPLICATION,		 // TAUB0I7 		  40
	  INVALID_OSAPPLICATION,		 // TAUB0I8 		  41
	  INVALID_OSAPPLICATION,		 // TAUB0I10		  42
	  INVALID_OSAPPLICATION,		 // TAUB0I12		  43
	  INVALID_OSAPPLICATION,		 // TAUB0I13		  44
	  INVALID_OSAPPLICATION,		 // TAUB0I14		  45
	  INVALID_OSAPPLICATION,		 // TAUB0I15		  46
	  INVALID_OSAPPLICATION,		 // UART3_Tx_		  47
	  INVALID_OSAPPLICATION,		 // UART3_Rx_		  48
	  INVALID_OSAPPLICATION,		 // UART3_Error 	  49
	  INVALID_OSAPPLICATION,	   //TAUD0I1     1ms_USS_CT
	  INVALID_OSAPPLICATION,		//TAUJ0I1     fixable_USS_CT
	  INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,        //INTDMA0
      INVALID_OSAPPLICATION,        //INTDMA1
      INVALID_OSAPPLICATION,        //INTDMA2
      INVALID_OSAPPLICATION,        //INTDMA3
      INVALID_OSAPPLICATION,        //INTDMA4
      INVALID_OSAPPLICATION,        //INTDMA5
      INVALID_OSAPPLICATION,        //INTDMA6
      INVALID_OSAPPLICATION,        //INTDMA7
      INVALID_OSAPPLICATION,        //INTDMA8
      INVALID_OSAPPLICATION,        //INTDMA9
      INVALID_OSAPPLICATION,        //INTDMA10
      INVALID_OSAPPLICATION,        //INTDMA11
      INVALID_OSAPPLICATION,        //INTDMA12
      INVALID_OSAPPLICATION,        //INTDMA13
      INVALID_OSAPPLICATION,        //INTDMA14
      INVALID_OSAPPLICATION,        //INTDMA15
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 9, is application trusted information */
   {
      0
   },
   /* Sub-Container 10, trusted functions */
   {
      0
   },
   /* Sub-Container 11, non trusted functions */
   {
      0
   },
   /* Sub-Container 12, Cat 2 ISR start addresses */
   {
		&CanIsrStatus_0func,       	/* ISR_CAN1ERR 0*/
		&CanIsrWakeup_0func,       	/* ISR_CAN1REC 1 INTP5 */
		&CanIsrTx_0func,          	/* ISR_CAN1TRX 2*/
		&CanIsrGlobalStatusfunc,  	/* ISR_CANGERR 3*/
		&CanIsrRxFifofunc,   	  	/* ISR_CANGRECC 4*/
		&ISR_TAUB0I0func,   		/* ISR_TAUB0I0 5*/
		&ISR_TAUD0I15func,   		/* ISR_TAUD0I15 6*/
		//&ISR_TAUJ0I0func,   		/* ISR_TAUJ0I0 7*/
		&ISR_TAUJ1I0func,   		/* ISR_TAUJ1I0 8*/
		&ISR_WDTA0func,   			/* ISR_WDTA0 9*/
		&ISR_IIC0RIfunc,			/* IIC0RI 10*/
		&ISR_IIC0TIfunc,			/* IIC0TI 11*/
		&ISR_IIC0TEIfunc,			/* IIC0TEI 12*/
		&ISR_IIC0EEfunc,			/* IIC0EE 13*/
		&ISR_ADCA0_INTSG1func,		/* ADCA0 14*/
		&CSIH1_Rx_handler,			/* CSIH1IR 15*/
		&CSIH1_Tx_handler,			/* CSIH1IC 16*/	
		&UART0_Tx_Handler,			/* UART0_TX 17*/
		&UART0_Rx_Handler,			/* UART0_RX 18*/	
		&UART0_Error_Handler,		/* UART0_Error 19*/
		&ISR_OSTM0func,				/* OSTM0 20*/
		&CSIH0_Rx_handler,			/* CSIH0IR 21*/
		&CSIH0_Tx_handler,			/* CSIH0IC 22*/	
		&CSIH0_Error_handler,		/* CSIH0IRE 23*/
		&CSIH1_Error_handler,		/* CSIH1IRE 24*/	   
		&ISR_TAUD0I6func,   		/* 25 TAUD0I6 */
		&ISR_TAUJ1I2func,   		/* 26 TAUJ1I2 */
		&ISR_INTP6_Handler, 		/* 27 INTP6 */
		&ISR_TAUD0I2_handler,   	/* 28 TAUD0I2*/
		&UART1_Tx_Handler,			/* 29 UART1_TX*/
		&UART1_Rx_Handler, 			/* 30 UART1_rx*/ 
		&UART1_Error_Handler,		/* 31 UART1_Error*/
		&ISR_INTP3_Handler,			/* 32 TINTP3*/
		&ISR_TAUB0I11func,			/* 33 TAUB0I11*/
		&ISR_ADCA1_INTSG1func,		/* 34 ADCA1_INTSG1*/
		&ISR_TAUB0I2func,			/* 35 TAUB0I2*/
		&ISR_TAUB0I4func,			/* 36 TAUB0I4*/
		&ISR_TAUB0I5func,			/* 37 TAUB0I5*/
		&ISR_TAUB0I6func,			/* 38 TAUB0I6*/
		&ISR_TAUB0I7func,			/* 39 TAUB0I7*/
		&ISR_TAUB0I8func,			/* 40 TAUB0I8*/
		&ISR_TAUB0I10func,			/* 41 TAUB0I10*/
		&ISR_TAUB0I12func,			/* 42 TAUB0I12*/
		&ISR_TAUB0I13func,			/* 43 TAUB0I13*/
		&ISR_TAUB0I14func,			/* 44 TAUB0I14*/
		&ISR_TAUB0I15func,			/* 45 TAUB0I15*/
		&UART3_Tx_Handler,			/* 46 EOLUART3_TX*/
		&UART3_Rx_Handler, 			/* 47 EOLUART3_rx*/ 
		&UART3_Error_Handler,		/* 48 EOLUART3_Error*/
		&UART4_Tx_Handler,			/* 49 M4UART4_TX*/
		&UART4_Rx_Handler, 			/* 50 M4UART4_rx*/ 
		&UART4_Error_Handler,		/* 51 M4UART4_Error*/
		&ISR_TAUD0I1func,			//TAUD0I1     1ms_USS_CT
		&ISR_TAUJ0I1func,		//TAUJ0I1     fixable_USS_CT
		&CanIsrStatus_1func,       	/* ISR_CAN1ERR 0*/
		&CanIsrWakeup_1func,       	/* ISR_CAN1REC 1 INTP5 */
		&CanIsrTx_1func,          	/* ISR_CAN1TRX 2*/
		&ISR_TAUJ1I1func,
		&ISR_INTDMA0_CAT2_func,          /*ISR_INTDMA0_CAT2*/
		&ISR_INTDMA1_CAT2_func,          /*ISR_INTDMA1_CAT2*/
		&ISR_INTDMA2_CAT2_func,          /*ISR_INTDMA2_CAT2*/
		&ISR_INTDMA3_CAT2_func,          /*ISR_INTDMA3_CAT2*/
		&ISR_INTDMA4_CAT2_func,          /*ISR_INTDMA4_CAT2*/
		&ISR_INTDMA5_CAT2_func,          /*ISR_INTDMA5_CAT2*/
		&ISR_INTDMA6_CAT2_func,          /*ISR_INTDMA6_CAT2*/
		&ISR_INTDMA7_CAT2_func,          /*ISR_INTDMA7_CAT2*/
		&ISR_INTDMA8_CAT2_func,          /*ISR_INTDMA8_CAT2*/
		&ISR_INTDMA9_CAT2_func,          /*ISR_INTDMA9_CAT2*/
		&ISR_INTDMA10_CAT2_func,         /*ISR_INTDMA10_CAT2*/
		&ISR_INTDMA11_CAT2_func,         /*ISR_INTDMA11_CAT2*/
		&ISR_INTDMA12_CAT2_func,         /*ISR_INTDMA12_CAT2*/
		&ISR_INTDMA13_CAT2_func,         /*ISR_INTDMA13_CAT2*/
		&ISR_INTDMA14_CAT2_func,         /*ISR_INTDMA14_CAT2*/
		&ISR_INTDMA15_CAT2_func,         /*ISR_INTDMA15_CAT2*/
	(osIsrFctType)0
   },
   /* Sub-Container 13, Cat 2 ISR nestable */
   {
	  osdFALSE, 		// CANGERR			 1
	  osdFALSE, 		// INTP10			 2
	  osdFALSE, 		// CAN1TRX			 3
	  osdFALSE, 		// CAN1ERR			 4
	  osdFALSE, 		// CANGRECC 		 5
	  osdFALSE, 		// TAUB0I0			 6
	  osdFALSE, 		// TAUD0I15 		 7
	  //osdFALSE, 		// TAUJ0I0			 8
	  osdFALSE, 		// TAUJ1I0			 9
	  osdFALSE, 		// WDTA0			 10
	  osdFALSE, 		// CSIH0IR			 11
	  osdFALSE, 		// IIC0TI			 12
	  osdFALSE, 		// IIC0TEI			 13
	  osdFALSE, 		// IIC0EE			 14
	  osdFALSE, 		// ADCA0_INTSG1 	 15
	  osdFALSE, 		// CSIH1IR			 16
	  osdFALSE, 		// CSIH1IC			 17
	  osdFALSE, 		// UART0_Tx_		 18
	  osdFALSE, 		// UART0_Rx_		 19
	  osdFALSE, 		// UART0_Error		 20
	  osdFALSE, 		// OSTM0			 21
	  osdFALSE, 		// CSIH0IR			 22
	  osdFALSE, 		// CSIH0IC			 23
	  osdFALSE, 		// CSIH0IRE 		 24
	  osdFALSE, 		// CSIH1IRE 		 25
	  osdFALSE, 		// TAUD0I6			 26
	  osdFALSE, 		// TAUD0I2			 27
	  osdFALSE, 		// INTP6			 28
	  osdFALSE, 		// TAUJ1I2			 29
	  osdFALSE, 		// UART1_Tx_		 30
	  osdFALSE, 		// UART1_Rx_		 31
	  osdFALSE, 		// UART1_Error		 32
	  osdFALSE, 		// INTP3			 33
	  osdFALSE, 		// TAUB0I11 		 34
	  osdFALSE, 		// ADCA1_INTSG1 	 35
	  osdFALSE, 		// TAUB0I2			 36
	  osdFALSE, 		// TAUB0I4			 37
	  osdFALSE, 		// TAUB0I5			 38
	  osdFALSE, 		// TAUB0I6			 39
	  osdFALSE, 		// TAUB0I7			 40
	  osdFALSE, 		// TAUB0I8			 41
	  osdFALSE, 		// TAUB0I10 		 42
	  osdFALSE, 		// TAUB0I12 		 43
	  osdFALSE, 		// TAUB0I13 		 44
	  osdFALSE, 		// TAUB0I14 		 45
	  osdFALSE, 		// TAUB0I15 		 46
	  osdFALSE, 		// UART3_Tx_		 47
	  osdFALSE, 		// UART3_Rx_		 48
	  osdFALSE, 		// UART3_Error		 49
	  osdFALSE, 	    // UART4_Tx_		 50
	  osdFALSE,		    // UART4_Rx_		 51
	  osdFALSE,		    // UART4_Error	     52
	  osdFALSE, 		  //TAUD0I1     1ms_USS_CT
	  osdFALSE,			//TAUJ0I1     fixable_USS_CT
	  osdFALSE,			// TAUJ1I1
	  osdFALSE,         //INTDMA0
	  osdFALSE,         //INTDMA1
	  osdFALSE,         //INTDMA2
	  osdFALSE,         //INTDMA3
	  osdFALSE,         //INTDMA4
	  osdFALSE,         //INTDMA5
	  osdFALSE,         //INTDMA6
	  osdFALSE,         //INTDMA7
	  osdFALSE,         //INTDMA8
	  osdFALSE,         //INTDMA9
	  osdFALSE,         //INTDMA10
	  osdFALSE,         //INTDMA11
	  osdFALSE,         //INTDMA12
	  osdFALSE,         //INTDMA13
	  osdFALSE,         //INTDMA14
	  osdFALSE,         //INTDMA15
      (osuint8)0
   },
   /* Sub-Container 14, ProcessToCore */
   {
	  0U,				  // CANGERR		   1
	  0U,				  // INTP10 		   2
	  0U,				  // CAN1TRX		   3
	  0U,				  // CAN1ERR		   4
	  0U,				  // CANGRECC		   5
	  0U,				  // TAUB0I0		   6
	  0U,				  // TAUD0I15		   7
	  //0U,				  // TAUJ0I0		   8
	  0U,				  // TAUJ1I0		   9
	  0U,				  // WDTA0			   10
	  0U,				  // CSIH0IR		   11
	  0U,				  // IIC0TI 		   12
	  0U,				  // IIC0TEI		   13
	  0U,				  // IIC0EE 		   14
	  0U,				  // ADCA0_INTSG1	   15
	  0U,				  // CSIH1IR		   16
	  0U,				  // CSIH1IC		   17
	  0U,				  // UART0_Tx_		   18
	  0U,				  // UART0_Rx_		   19
	  0U,				  // UART0_Error	   20
	  0U,				  // OSTM0			   21
	  0U,				  // CSIH0IR		   22
	  0U,				  // CSIH0IC		   23
	  0U,				  // CSIH0IRE		   24
	  0U,				  // CSIH1IRE		   25
	  0U,				  // TAUD0I6		   26
	  0U,				  // TAUD0I2		   27
	  0U,				  // INTP6			   28
	  0U,				  // TAUJ1I2		   29
	  0U,				  // UART1_Tx_		   30
	  0U,				  // UART1_Rx_		   31
	  0U,				  // UART1_Error	   32
	  0U,				  // INTP3			   33
	  0U,				  // TAUB0I11		   34
	  0U,				  // ADCA1_INTSG1	   35
	  0U,				  // TAUB0I2		   36
	  0U,				  // TAUB0I4		   37
	  0U,				  // TAUB0I5		   38
	  0U,				  // TAUB0I6		   39
	  0U,				  // TAUB0I7		   40
	  0U,				  // TAUB0I8		   41
	  0U,				  // TAUB0I10		   42
	  0U,				  // TAUB0I12		   43
	  0U,				  // TAUB0I13		   44
	  0U,				  // TAUB0I14		   45
	  0U,				  // TAUB0I15		   46
	  0U,				  // UART3_Tx_		   47
	  0U,				  // UART3_Rx_		   48
	  0U,				  // UART3_Error	   49
	  0U,				  // UART4_Tx_		   50
	  0U,				  // UART4_Rx_		   51
	  0U,				  // UART4_Error	   52
	  0U,	              //TAUD0I1     1ms_USS_CT
	  0U,					//TAUJ0I1     fixable_USS_CT
	  0U, 	             // TAUJ0I1
	  0U,               //INTDMA0
	  0U,               //INTDMA1
	  0U,               //INTDMA2
	  0U,               //INTDMA3
	  0U,               //INTDMA4
	  0U,               //INTDMA5
	  0U,               //INTDMA6
	  0U,               //INTDMA7
	  0U,               //INTDMA8
	  0U,               //INTDMA9
	  0U,               //INTDMA10
	  0U,               //INTDMA11
	  0U,               //INTDMA12
	  0U,               //INTDMA13
	  0U,               //INTDMA14
	  0U,               //INTDMA15
      (CoreIdType)0
   },
   /* Sub-Container 15, AlarmToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 16, ResourceToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 17, CounterToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 18, ScheduleTableToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 19, ApplicationToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 20, TrustedFunctionToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 21, NonTrustedFunctionToCore */
   {
      (CoreIdType)0
   },
   /* Sub-Container 22, Core Control Block addresses */
   {
      &osCtrlVarsCore0,
      (osCtrlVarType*)0
   },
   /* Sub-Container 23, peripheral regions */
   {
      0
   },
   /* Sub-Container 24, Spinlock lock method */
   {
      (osuint8)0
   },
   /* Sub-Container 25, Spinlock lock type */
   {
      (osuint8)0
   },
   /* Sub-Container 26, Optimized Spinlock variables */
   {
      (osMiniLockType*) osdNULL
   },
   /* Sub-Container 27 ISR stack information */
   {
      {
         (osStackPtrType)osdISR_Level3_BOT,		// CANGERR 		  1
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,		// INTP10			  2
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,		// CAN1TRX 		  3
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,		// CAN1ERR 		  4
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT, 		// CANGRECC	 		  5
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I0 		  6
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level0_BOT,		//CANGRECC		7
         (osStackPtrType)osdISR_Level0_TOP
      },
//      {
//         (osStackPtrType)osdISR_Level2_BOT,		// TAUJ0I0 		  8
//         (osStackPtrType)osdISR_Level2_TOP
//      },
      {
         (osStackPtrType)osdISR_Level3_BOT,
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// WDTA0			  10
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// CSIH0IR 		  11
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// IIC0TI			  12
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// IIC0TEI 		  13
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// IIC0EE			  14
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// ADCA0_INTSG1	  15
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// CSIH1IR 		  16
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// CSIH1IC 		  17
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// UART0_Tx_		  18
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// UART0_Rx_		  19
         (osStackPtrType)osdISR_Level3_TOP
      },      
      {
         (osStackPtrType)osdISR_Level3_BOT,			// UART0_Error 	  20
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// OSTM0			  21
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,			// CSIH0IR 		  22
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,		// CSIH0IC 		  23
         (osStackPtrType)osdISR_Level3_TOP
      },          
      {
         (osStackPtrType)osdISR_Level3_BOT,		// CSIH0IRE		  24
         (osStackPtrType)osdISR_Level3_TOP
      },     
      {
         (osStackPtrType)osdISR_Level3_BOT,		// CSIH1IRE		  25
         (osStackPtrType)osdISR_Level3_TOP
      },
     
      {
         (osStackPtrType)osdISR_Level3_BOT,		// TAUD0I6 		  26
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level3_BOT,		// TAUD0I2 		  27
         (osStackPtrType)osdISR_Level3_TOP
      },          
      {
         (osStackPtrType)osdISR_Level3_BOT,		// INTP6			  28
         (osStackPtrType)osdISR_Level3_TOP
      },    
      {
         (osStackPtrType)osdISR_Level3_BOT,		// TAUJ1I2 		  29
         (osStackPtrType)osdISR_Level3_TOP
      },   
  	  {
         (osStackPtrType)osdISR_Level3_BOT,		// UART1_Tx_		  30
         (osStackPtrType)osdISR_Level3_TOP
      },  
	  {
		 (osStackPtrType)osdISR_Level3_BOT,		// UART1_Rx_		  31
		 (osStackPtrType)osdISR_Level3_TOP
	  },	   
	  {
		 (osStackPtrType)osdISR_Level3_BOT,		// UART1_Error 	  32
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
	  	 (osStackPtrType)osdISR_Level3_BOT,		// INTP3			  33
	  	 (osStackPtrType)osdISR_Level3_TOP
      },      
	  {
		 (osStackPtrType)osdISR_Level3_BOT,		// TAUB0I11		  34
		 (osStackPtrType)osdISR_Level3_TOP
	  }, 
	  {
         (osStackPtrType)osdISR_Level3_BOT,		// ADCA1_INTSG1	  35
         (osStackPtrType)osdISR_Level3_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I2 		  36
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I4 		  37
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I5 		  38
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I6 		  39
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I7 		  40
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I8 		  41
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I10		  42
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
        (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I12		  43
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I13		  44
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I14		  45
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_Level1_BOT,		// TAUB0I15		  46
         (osStackPtrType)osdISR_Level1_TOP
      },
      {
         (osStackPtrType)osdISR_ADD_BOT,		// UART3_Tx_		  49
         (osStackPtrType)osdISR_ADD_TOP
      },  
	  {
		 (osStackPtrType)osdISR_ADD_BOT,		// UART3_Rx_		  50
		 (osStackPtrType)osdISR_ADD_TOP
	  },	   
	  {
		 (osStackPtrType)osdISR_ADD_BOT,		// UART3_Error 	  51
	     (osStackPtrType)osdISR_ADD_TOP
	  },
	  {
         (osStackPtrType)osdISR_ADD_BOT,		// UART4_Tx_		  52
         (osStackPtrType)osdISR_ADD_TOP
      },  
	  {
		 (osStackPtrType)osdISR_ADD_BOT,		// UART4_Rx_		  53
		 (osStackPtrType)osdISR_ADD_TOP
	  },	   
	  {
		 (osStackPtrType)osdISR_ADD_BOT,		// UART4_Error 	  54
	     (osStackPtrType)osdISR_ADD_TOP
	  },
	  {
 	    (osStackPtrType)osdISR_Level4_BOT,		  //TAUD0I1     1ms_USS_CT
 	    (osStackPtrType)osdISR_Level4_TOP
 	  },
 	  {
 	    (osStackPtrType)osdISR_Level2_BOT,		  //TAUJ0I1     fixable_USS_CT
 	    (osStackPtrType)osdISR_Level2_TOP
 	  },
 	   {
 	    (osStackPtrType)osdISR_Level2_BOT,		  //TAUJ1I1     
 	    (osStackPtrType)osdISR_Level2_TOP
 	  },
 	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA0
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA1
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA2
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA3
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA4
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA5
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA6
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA7
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA8
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA9
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA10
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA11
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA12
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA13
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA14
	     (osStackPtrType)osdISR_Level3_TOP
	  },
	  {
		 (osStackPtrType)osdISR_Level3_BOT,         //INTDMA15
	     (osStackPtrType)osdISR_Level3_TOP
	  },
      {
         (osStackPtrType)0,
         (osStackPtrType)0
      }
   },

   /* Sub-Container 28: ISR interrupt channel index */
   {
      (osuint16) 24, /* channel of ISR_CAN1ERR 0*/
      (osuint16) 45, /* channel of ISR_INTP10 1*/
      (osuint16) 26, /* channel of ISR_CAN1TRX 2*/
      (osuint16) 22, /* channel of ISR_CANGERR 3*/
      (osuint16) 23, /* channel of ISR_CANGRECC 4*/
      (osuint16) 142, /* channel of ISR_TAUB0I0 5*/
      (osuint16) 55, /* channel of ISR_TAUD0I15 6*/
     // (osuint16) 80, /* channel of ISR_TAUJ0I0 7*/
      (osuint16) 168, /* channel of ISR_TAUJ1I0 8*/
      (osuint16) 40, /* channel of ISR_WDTA0 9*/
      (osuint16) 78, 		// IIC0RI 		10
      (osuint16) 76,		// IIC0TI 		11
      (osuint16) 79,		//IIC0TEI 		12
      (osuint16) 77,		//IIC0EE		13
      (osuint16) 18,		//ADCA0 SG1 	14  
      (osuint16) 117,		//ICCSIH1IR		15
      (osuint16) 116,		//ICCSIH1IC 	16     
      (osuint16) 34,		// UART0 TX		17
      (osuint16) 35,		//uart_rx		18
      (osuint16) 36,      	//uart_error	19
      (osuint16) 84,     	//OSTM0			20
      (osuint16) 30,		// CSIH0 IR		21
      (osuint16) 29,		//CSIH0 IC		22
      (osuint16) 31,      	// CSIH0IRE		23
      (osuint16) 118,      	//CSIH1IRE		24
      (osuint16) 11,   		//ISR_TAUD0I6	25
      (osuint16) 170,    	//ISR_TAUJ1I2	26 
      (osuint16) 128,		//INTP6			27
      (osuint16) 9,		    //TAUD0I2	   	28
      (osuint16) 121,       //UART1_Tx_Handler		29
      (osuint16) 122,       //UART1_Rx_Handler		30
      (osuint16) 123,       //UART1_Error_Handler	31
	  (osuint16) 42,		//INTP3			32
	  (osuint16) 153,		//INTTAUB0I11	33
 	  (osuint16) 213,		//ADCA1 SG1		34 
	  (osuint16) 144,       //INTTAUB0I2  	36
	  (osuint16) 146,		//INTTAUB0I4	37
	  (osuint16) 147,		//INTTAUB0I5	38
	  (osuint16) 148,		//INTTAUB0I6	39
	  (osuint16) 149,		//INTTAUB0I7	40
	  (osuint16) 150,		//INTTAUB0I8	41
	  (osuint16) 152,		//INTTAUB0I10   35
	  (osuint16) 154,		//INTTAUB0I12	42
	  (osuint16) 155,		//INTTAUB0I13	43
	  (osuint16) 156,		//INTTAUB0I14	44
	  (osuint16) 157,		//INTTAUB0I15	45
	  (osuint16) 229,       //UART3_Tx_Handler		46
      (osuint16) 230,       //UART3_Rx_Handler		47
      (osuint16) 231,       //UART3_Error_Handler	48
      (osuint16) 233,       //UART4_Tx_Handler		49
      (osuint16) 234,       //UART4_Rx_Handler		50
      (osuint16) 235,       //UART4_Error_Handler	51
      (osuint16) 48,	  //TAUD0I1     1ms_USS_CT
	  (osuint16) 81,	  //TAUJ0I1     fixable_USS_CT
	  (osuint16) 113, /* channel of ISR_CAN1ERR 0*/
      (osuint16) 46, /* channel of ISR_INTP10 1*/
      (osuint16) 115, /* channel of ISR_CAN1TRX 2*/
      (osuint16) 169, // TAUJ1I1
      (osuint16) 60,    //INTDMA0
      (osuint16) 61,    //INTDMA1
      (osuint16) 62,    //INTDMA2
      (osuint16) 63,    //INTDMA3
      (osuint16) 64,    //INTDMA4
      (osuint16) 65,    //INTDMA5
      (osuint16) 66,    //INTDMA6
      (osuint16) 67,    //INTDMA7
      (osuint16) 68,    //INTDMA8
      (osuint16) 69,    //INTDMA9
      (osuint16) 70,    //INTDMA10
      (osuint16) 71,    //INTDMA11
      (osuint16) 72,    //INTDMA12
      (osuint16) 73,    //INTDMA13
      (osuint16) 74,    //INTDMA14
      (osuint16) 75,    //INTDMA15
      (osuint16) 0  /* empty */
   },

   /* Sub-Container 29: ISR interrupt priority level */
   {
		 (osuint16)0x0003,		   // CANGERR			1
		 (osuint16)0x0003,		   // INTP10			2
		 (osuint16)0x0003,		   // CAN1TRX			3
		 (osuint16)0x0003,		   // CAN1ERR			4
		 (osuint16)0x0003,		   // CANGRECC			5
		 (osuint16)0x0001,		   // TAUB0I0			6
		 (osuint16)0x0000,		   // TAUD0I15			7
		// (osuint16)0x0002,		   // TAUJ0I0			8
		 (osuint16)0x0003,		   // TAUJ1I0			9
		 (osuint16)0x0003,		   // WDTA0 			10
		 (osuint16)0x0003,		   // CSIH0IR			11
		 (osuint16)0x0003,	   		// IIC0TI			12
		 (osuint16)0x0003,	   		// IIC0TEI			13
		 (osuint16)0x0003,	   		// IIC0EE			14
		 (osuint16)0x0003,	   		// ADCA0_INTSG1		15
		 (osuint16)0x0003,		   // CSIH1IR			16
		 (osuint16)0x0003,		   // CSIH1IC			17
		 (osuint16)0x0003,		   // UART0_Tx_ 		18
		 (osuint16)0x0003,		   // UART0_Rx_ 		19
		 (osuint16)0x0003,		   // UART0_Error		20
		 (osuint16)0x0003,		   // OSTM0 			21
		 (osuint16)0x0003,		   // CSIH0IR			22
		 (osuint16)0x0003,		   // CSIH0IC			23
		 (osuint16)0x0003,		   // CSIH0IRE			24
		 (osuint16)0x0003,		   // CSIH1IRE			25
		 (osuint16)0x0003,		   // TAUD0I6			26
		 (osuint16)0x0003,		   // TAUD0I2			27
		 (osuint16)0x0003,		   // INTP6 			28
		 (osuint16)0x0003,		   // TAUJ1I2			29
		 (osuint16)0x0003,		   // UART1_Tx_ 		30
		 (osuint16)0x0003,		   // UART1_Rx_ 		31
		 (osuint16)0x0003,		   // UART1_Error		32
		 (osuint16)0x0003,		   // INTP3 			33
		 (osuint16)0x0003,		   // TAUB0I11			34
		 (osuint16)0x0003,		   // ADCA1_INTSG1		35
		 (osuint16)0x0001,		   // TAUB0I2			36
		 (osuint16)0x0001,		   // TAUB0I4			37
		 (osuint16)0x0001,		   // TAUB0I5			38
		 (osuint16)0x0001,		   // TAUB0I6			39
		 (osuint16)0x0001,		   // TAUB0I7			40
		 (osuint16)0x0001,		   // TAUB0I8			41
		 (osuint16)0x0001,		   // TAUB0I10			42
		 (osuint16)0x0001,		   // TAUB0I12			43
		 (osuint16)0x0001,		   // TAUB0I13			44
		 (osuint16)0x0001,		   // TAUB0I14			45
		 (osuint16)0x0001,		   // TAUB0I15			46
		 (osuint16)0x0003,		   // UART3_Tx_ 		47
		 (osuint16)0x0003,		   // UART3_Rx_ 		48
		 (osuint16)0x0003,		   // UART3_Error		49
		 (osuint16)0x0003,		   // UART4_Tx_ 		50
		 (osuint16)0x0003,		   // UART4_Rx_ 		51
		 (osuint16)0x0003,		   // UART4_Error		52
		 (osuint16)0x0004,			//TAUD0I1     1ms_USS_CT
		 (osuint16)0x0002,			//TAUJ0I1     fixable_USS_CT
		 (osuint16)0x0002,			// TAUJ1I1
		 (osuint16)0x0003,          //INTDMA0
		 (osuint16)0x0003,          //INTDMA1
		 (osuint16)0x0003,          //INTDMA2
		 (osuint16)0x0003,          //INTDMA3
		 (osuint16)0x0003,          //INTDMA4
		 (osuint16)0x0003,          //INTDMA5
		 (osuint16)0x0003,          //INTDMA6
		 (osuint16)0x0003,          //INTDMA7
		 (osuint16)0x0003,          //INTDMA8
		 (osuint16)0x0003,          //INTDMA9
		 (osuint16)0x0003,          //INTDMA10
		 (osuint16)0x0003,          //INTDMA11
		 (osuint16)0x0003,          //INTDMA12
		 (osuint16)0x0003,          //INTDMA13
		 (osuint16)0x0003,          //INTDMA14
		 (osuint16)0x0003,          //INTDMA15
		 (osuint16)0x0000
   },

   /* Sub-Container 30: ISR to Core assignment */
   {
	  0U,				  // CANGERR		   1
	  0U,				  // INTP10 		   2
	  0U,				  // CAN1TRX		   3
	  0U,				  // CAN1ERR		   4
	  0U,				  // CANGRECC		   5
	  0U,				  // TAUB0I0		   6
	  0U,				  // TAUD0I15		   7
	 // 0U,				  // TAUJ0I0		   8
	  0U,				  // TAUJ1I0		   9
	  0U,				  // WDTA0			   10
	  0U,				  // CSIH0IR		   11
	  0U,				  // IIC0TI 		   12
	  0U,				  // IIC0TEI		   13
	  0U,				  // IIC0EE 		   14
	  0U,				  // ADCA0_INTSG1	   15
	  0U,				  // CSIH1IR		   16
	  0U,				  // CSIH1IC		   17
	  0U,				  // UART0_Tx_		   18
	  0U,				  // UART0_Rx_		   19
	  0U,				  // UART0_Error	   20
	  0U,				  // OSTM0			   21
	  0U,				  // CSIH0IR		   22
	  0U,				  // CSIH0IC		   23
	  0U,				  // CSIH0IRE		   24
	  0U,				  // CSIH1IRE		   25
	  0U,				  // TAUD0I6		   26
	  0U,				  // TAUD0I2		   27
	  0U,				  // INTP6			   28
	  0U,				  // TAUJ1I2		   29
	  0U,				  // UART1_Tx_		   30
	  0U,				  // UART1_Rx_		   31
	  0U,				  // UART1_Error	   32
	  0U,				  // INTP3			   33
	  0U,				  // TAUB0I11		   34
	  0U,				  // ADCA1_INTSG1	   35
	  0U,				  // TAUB0I2		   36
	  0U,				  // TAUB0I4		   37
	  0U,				  // TAUB0I5		   38
	  0U,				  // TAUB0I6		   39
	  0U,				  // TAUB0I7		   40
	  0U,				  // TAUB0I8		   41
	  0U,				  // TAUB0I10		   42
	  0U,				  // TAUB0I12		   43
	  0U,				  // TAUB0I13		   44
	  0U,				  // TAUB0I14		   45
	  0U,				  // TAUB0I15		   46
	  0U,				  // UART3_Tx_		   47
	  0U,				  // UART3_Rx_		   48
	  0U,				  // UART3_Error	   49
	  0U,				  // UART4_Tx_		   50
	  0U,				  // UART4_Rx_		   51
	  0U,				  // UART4_Error	   52
	  0U,				 //TAUD0I1     1ms_USS_CT
	  0U,				//TAUJ0I1     fixable_USS_CT
	  0U,				// TAUJ0I1
	  0U,               //INTDMA0
	  0U,               //INTDMA1
	  0U,               //INTDMA2
	  0U,               //INTDMA3
	  0U,               //INTDMA4
	  0U,               //INTDMA5
	  0U,               //INTDMA6
	  0U,               //INTDMA7
	  0U,               //INTDMA8
	  0U,               //INTDMA9
	  0U,               //INTDMA10
	  0U,               //INTDMA11
	  0U,               //INTDMA12
	  0U,               //INTDMA13
	  0U,               //INTDMA14
	  0U,               //INTDMA15
      0U
   },

   (osuint32)0 /* uiCheckSum */
};

#pragma ghs section rodata=default
#pragma ghs section rosdata=default

